# Generated by Django 4.1.2 on 2022-11-24 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Policlinic', '0002_policlinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('policlinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Policlinic.policlinic')),
            ],
        ),
    ]
