# Generated by Django 4.1.2 on 2022-12-07 18:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Policlinic', '0004_alter_images_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policlinic',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
