# Generated by Django 4.1.2 on 2022-12-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policlinic', '0011_remove_doctors_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='doctors',
            name='twitter',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
