# Generated by Django 4.1.2 on 2022-12-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policlinic', '0012_doctors_linkedin_doctors_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
