# Generated by Django 4.1.2 on 2022-12-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policlinic', '0014_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='insurance',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
