# Generated by Django 4.1.2 on 2022-12-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policlinic', '0018_alter_appointment_email_alter_appointment_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='note',
            field=models.TextField(max_length=200),
        ),
    ]
