# Generated by Django 4.1.2 on 2022-12-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policlinic', '0020_alter_appointment_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
