# Generated by Django 4.1.2 on 2022-12-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Policlinic', '0022_alter_appointment_insurance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
