# Generated by Django 4.1.2 on 2022-12-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Policlinic', '0026_alter_randevu_doctor_alter_randevu_policlinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='doctor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Policlinic.doctors'),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='insurance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='note',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='payment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='policlinic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Policlinic.policlinic'),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
