# Generated by Django 4.1.2 on 2022-12-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Policlinic', '0027_alter_randevu_date_alter_randevu_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Policlinic.doctors'),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='policlinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Policlinic.policlinic'),
        ),
    ]
