# Generated by Django 4.1.2 on 2022-12-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policlinic', '0028_alter_randevu_doctor_alter_randevu_policlinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
