# Generated by Django 4.1.2 on 2022-12-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policlinic', '0031_randevu_doctor_randevu_policlinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('True', 'Onaylandı'), ('False', 'Onaylanmadı')], default='New', max_length=15),
        ),
    ]
