# Generated by Django 4.1.2 on 2022-12-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policlinic', '0032_alter_randevu_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='doctor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='insurance',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='note',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='payment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='policlinic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
