# Generated by Django 4.1.2 on 2022-12-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_faq_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
