# Generated by Django 4.1.2 on 2022-12-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='saturday',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='setting',
            name='sunday',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='setting',
            name='weekdays',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
