# Generated by Django 4.1.2 on 2022-12-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_setting_saturday_setting_sunday_setting_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='saturday',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='setting',
            name='sunday',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='setting',
            name='weekdays',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
