# Generated by Django 4.1.2 on 2022-12-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_setting_saturday_alter_setting_sunday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact_map',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
