# Generated by Django 4.1.2 on 2022-12-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_setting_address_alter_setting_contact_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='contact_map',
            field=models.CharField(max_length=500),
        ),
    ]
